export const keys = {
  GET_POSTS_DELETE: ['GET_POSTS_DELETE'],
  GET_POSTS_UPDATE: ['GET_POSTS_UPDATE'],
  GET_POSTS: ['GET_POSTS'],
  GET_LIKE_POSTS: ['GET_LIKE_POSTS'],
  GET_BEST_POSTS: ['GET_BEST_POSTS'],
  GET_ALCOHOLS: ['GET_ALCOHOLS'],
  GET_LIKE_STORE: ['GET_LIKE_STORE'],
  GET_ALL_ALCOHOLS: ['GET_ALL_ALCOHOLS'],
};
